CREATE TABLE DRIVER(
    DRIV_ID INT,
    DRIV_LNAME VARCHAR2(50),
    DRIV_FNAME VARCHAR2(50),
    DRIV_PHONE VARCHAR2(20),
    LICENSE_NUM VARCHAR2(20),
    DRIV_LONGITUDE FLOAT,
    DRIV_LATITUDE FLOAT,
    DRIV_STATUS VARCHAR2(20),
    CONSTRAINT PK_DRIVER PRIMARY KEY (DRIV_ID)
);

CREATE TABLE PASSENGER(
    PASS_ID INT,
    PASS_LNAME VARCHAR2(50),
    PASS_FNAME VARCHAR2(50),
    PASS_PHONE VARCHAR2(20),
    PASS_EMAIL VARCHAR2(100),
    CONSTRAINT PK_PASSENGER PRIMARY KEY (PASS_ID)
);

CREATE TABLE RIDE(
    RIDE_ID INT,
    DRIV_ID INT,
    PASS_ID INT,
    REQUEST_TIME TIMESTAMP,
    PICKUP_LOCATION VARCHAR2(100),
    DROPOFF_LOCATION VARCHAR2(100),
    DIST_TRAVELED FLOAT,
    BASE_FARE FLOAT,
    TRIP_DURATION FLOAT,
    DEMSUR_MULTIPLIER FLOAT,
    CONSTRAINT PK_RIDE PRIMARY KEY (RIDE_ID),
    CONSTRAINT FK_RIDE_DRIVER FOREIGN KEY(DRIV_ID) REFERENCES DRIVER(DRIV_ID),
    CONSTRAINT FK_RIDE_PASSENGER FOREIGN KEY(PASS_ID) REFERENCES PASSENGER(PASS_ID)
);

CREATE TABLE PAYMENT(
    PAY_ID INT,
    RIDE_ID INT,
    PAY_DATE DATE,
    PAY_AMOUNT FLOAT,
    PAY_METHOD VARCHAR2(50),
    PAY_STATUS VARCHAR2(20),
    CONSTRAINT PK_PAYMENT PRIMARY KEY (PAY_ID),
    CONSTRAINT FK_PAYMENT_RIDE FOREIGN KEY(RIDE_ID) REFERENCES RIDE(RIDE_ID)
);

CREATE TABLE DRIVER_LOCATION(
    DRIV_ID INT,
    DRIV_TIMESTAMP TIMESTAMP,
    LONGITUDE FLOAT,
    LATITUDE FLOAT,
    CONSTRAINT PK_DRIVER_LOCATION PRIMARY KEY (DRIV_ID, DRIV_TIMESTAMP),
    CONSTRAINT FK_DRIVER_LOCATION_DRIVER FOREIGN KEY(DRIV_ID) REFERENCES DRIVER(DRIV_ID)
);

CREATE TABLE RIDE_SERVICE(
    SERV_TYPE_ID INT,
    RIDE_ID INT,
    APPLIED_RATE FLOAT,
    CONSTRAINT PK_RIDE_SERVICE PRIMARY KEY (SERVICE_TYPE_ID, RIDE_ID),
    CONSTRAINT FK_RIDE_SERVICE_SERVICE_TYPE FOREIGN KEY(SERV_TYPE_ID) REFERENCES SERVICE_TYPE(SERV_TYPE_ID),
    CONSTRAINT FK_RIDE_SERVICE_RIDE FOREIGN KEY(RIDE_ID) REFERENCES RIDE(RIDE_ID)
);

CREATE TABLE SERVICE_TYPE(
    SERV_TYPE_ID INT,
    SERV_NAME VARCHAR2(50),
    BASE_RATE FLOAT,
    CONSTRAINT PK_SERVICE_TYPE PRIMARY KEY (SERV_TYPE_ID)
);

CREATE TABLE AREA_LOC(
    AREA_ID INT,
    CITY_NAME VARCHAR2(50),
    STATE_NAME VARCHAR2(50),
    AREA_DENSITY FLOAT,
    CONSTRAINT PK_AREA PRIMARY KEY (AREA_ID)
);

CREATE TABLE DEMAND_SURGE(
    DEMSUR_ID INT,
    AREA_ID INT,
    STARTING_TIME DATE,
    ENDING_TIME DATE,
    DEMSUR_MULTIPLIER FLOAT,
    DEMSUR_REASON VARCHAR2(100),
    CONSTRAINT PK_DEMAND_SURGE PRIMARY KEY (DEMSUR_ID),
    CONSTRAINT FK_DEMAND_SURGE_AREA FOREIGN KEY(AREA_ID) REFERENCES AREA_LOC(AREA_ID)
);

CREATE TABLE WEATHER(
    WEATHER_ID INT,
    AREA_ID INT,
    WEAT_TIME DATE,
    WEAT_CONDITION VARCHAR2(50),
    TEMPERATURE FLOAT,
    CONSTRAINT PK_WEATHER PRIMARY KEY (WEATHER_ID),
    CONSTRAINT FK_WEATHER_AREA FOREIGN KEY(AREA_ID) REFERENCES AREA_LOC(AREA_ID)
);

CREATE TABLE SPECIAL_EVENT(
    EVENT_ID INT,
    AREA_ID INT,
    EVENT_NAME VARCHAR2(100),
    EVENT_STREET VARCHAR2(100),
    EVENT_ZIP VARCHAR2(10),
    BUILDING_NUM VARCHAR2(20),
    EVENT_START DATE,
    EVENT_END DATE,
    CONSTRAINT PK_SPECIAL_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_SPECIAL_EVENT_AREA FOREIGN KEY(AREA_ID) REFERENCES AREA_LOC(AREA_ID)
);